POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "G",
    "number": "1122345234544"
}

###

GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/609546187515b16494a08882

### 
PUT http://localhost:3001/api/persons/6094109167e0d14644ec1e90
Content-Type: application/json

{
    "name": "Tito",
    "number": "12341234"
}

###
GET http://localhost:3001/info