POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "BAT A",
    "number": "1128967344"
}

###

GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/6094067080a39b58b4863bfd

### 
PUT http://localhost:3001/api/persons/6094109167e0d14644ec1e90
Content-Type: application/json

{
    "name": "asdf",
    "number": "88888888"
}

###
GET http://localhost:3001/info